server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  cloud:
    config:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8888